### ISSUE TITLE
Build better chart/HTML display

### ISSUE THREAD

**Issue by tpetricek** [fslaborg/zzarchive-FsLab#89] opened 2015-05-12 20:22 UTC
When you create a chart (using XPlot or formerly using Foogle), FsLab just opens a new web browser window using `Process.Start`. This works OK, but it is a bit low-tech and limited.

It would be nice to have a better way of displaying HTML content produced by FsLab scripts (this could be useful for more things than just for charts - you could do the same for Deedle frames etc.)

So, I think it would be nice if FsLab had some built-in support for that. The best option I can think of is to build a simple Suave server that hosts HTML (+ JavaScript), perhaps with multiple tabs where you see different outputs...

We would still open this a web browser (but Xamarin, Atom, VS could override this and open this thing in a tool window), but at least you'd just have one page hosted via `localhost`, which could be used for all FsLab outputs...

**Comment by TahaHachana** [comment] 2015-05-13 17:40
I [experimented around this scenario](https://gist.github.com/TahaHachana/c50df99ace8b60ab5deb) using OWIN (and only with Google Charts) and managed to display charts in the same browser tab which reloads automatically every time the underlying HTML is updated.

The problem is the large number of required dependencies and I'm not sure if this works across platforms but it's still pretty interesting especially when FSI and the browser window are placed side by side.

**Comment by dsyme** [comment] 2020-12-10 20:10
FsLab is now changing to be an incubation space for F# data science projects, per discussion in https://github.com/fslaborg/zzarchive-FsLab/issues/137#issuecomment-741093688

Closing this out as it relates to the old FsLab package collection.

**Closed by dsyme** 2020-12-10 20:10 UTC
Labels: proposal, up-for-grabs
